apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-api
  labels:
    name: name-api
spec:
  replicas: 2
  selector:
    matchLabels: 
      name: name-api
  template:
    metadata:
      labels:
        name: name-api
    spec:
      containers:
      - name: name-api
        image: fenggaoyao/api2
        ports:
          - containerPort: 80


---

kind: Service
apiVersion: v1
metadata:
  name: name-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: name-api