apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-api
  namespace: netcore
  labels:
    name: name-api
spec:
  replicas: 2
  selector:
    matchLabels: 
      name: name-api
  template:
    metadata:
      labels:
        name: name-api
    spec:
      containers:
      - name: name-api
        env:
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
        image: fenggaoyao/api2:1.1
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent


---

kind: Service
apiVersion: v1
metadata:
  name: name-api
  namespace: netcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: name-api