apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings.name-api
  namespace: netcore
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Trace"
        }
      },
      "AllowedHosts": "*"
    }
  mykey: Hello World