apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api1-deploy
  labels:
    name: k8s-api1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: k8s-api1
  template:
    metadata:
      labels:
        name: k8s-api1
    spec:
      containers:
      - name: k8s-api1
        image: 	fenggaoyao/api1
        ports:
        - containerPort: 80


---

kind: Service
apiVersion: v1
metadata:
  name: k8s-api1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: k8s-api1
