apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings.name-api
  namespace: netcore
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Trace"
        }
      },
      "AllowedHosts": "*"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api1-deploy
  namespace: netcore
  labels:
    name: k8s-api1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: k8s-api1
  template:
    metadata:
      labels:
        name: k8s-api1
    spec:
      containers:
        - name: k8s-api1
          image: registry.cn-shenzhen.aliyuncs.com/cloudsu/k8s-demo:2.0
          volumeMounts:
            - name: appsettings 
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: aliyunapi1
      volumes:
        - name: appsettings          
          projected:
            sources:
            - configMap:
                name: appsettings.name-api


---
kind: Service
apiVersion: v1
metadata:
  name: k8s-api1
  namespace: netcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: k8s-api1



  



