version: '3.4'

services: 
  api1:
    container_name: gatesway
    image: fenggaoyao/api1
    build: 
      context: .
      dockerfile: api1/Dockerfile
    ports: 
      - "8080:80"
  
  api2:
    container_name: name-api
    image: fenggaoyao/api2
    build: 
      context: .
      dockerfile: api2/Dockerfile
    ports: 
     - "8081:80"
