apiVersion: v1
kind: Secret
metadata:
  name:  mysqlpassword
data:
   mysql_root_password:  cGFzc3dvcmQ=
type: Opaque



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: name
        image: mysql:5.6
        env:
        - name:  MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpassword
              key: mysql_root_password
        ports:
        - name:  mysql
          containerPort:  3306
        volumeMounts:
        - name:  mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name:   mysql-persistent-storage
          hostPath:
            path: /var/lib/mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

